### ISSUE TITLE
Can I use this method now?

### ISSUE THREAD

**Issue by matsu4ki** [tsaiDavid/slack-aim-notification#1]
I rewrite existing mp3 file, but sound wasn't change.
Was this method blocked by Slack?

**Comment by krry** [comment]
Same experience as @matsu4ki. I renamed a new sound to replace `hummus.mp3` and cleared cached and restarted Slack to no avail. Still hummus… :/

**Comment by byxor** [comment]
Same, it's like they're intentionally redownloading the original `hummus.mp3` from somewhere else

**Comment by matsu4ki** [comment]
This method is considered to have been blocked by Slack as several individuals were unable to implement it.
